const doctorsData = [
  {
    id: '1',
    name: 'Dr. John Smith',
    specialty: 'Cardiologia',
    medicalCenter: 'Clínica Corazón Saludable',
    patients: 1200,
    experience: '15 años',
    rating: 4.8,
    reviews: 320,
    aboutMe:
      'Especialista en cardiología con más de 15 años de experiencia ayudando a pacientes con problemas cardiovasculares.',
    workHours: 'Lunes a Viernes: 9:00 AM - 5:00 PM',
    imageUrl: 'https://example.com/doctor1.jpg',
  },
  {
    id: '2',
    name: 'Dra. Ana Pérez',
    specialty: 'Pediatría',
    medicalCenter: 'Hospital Infantil Alegría',
    patients: 900,
    experience: '10 años',
    rating: 4.9,
    reviews: 410,
    aboutMe: 'Apasionada por la salud infantil, con un enfoque en el desarrollo y bienestar de los niños.',
    workHours: 'Lunes a Viernes: 8:00 AM - 3:00 PM',
    imageUrl: 'https://example.com/doctor2.jpg',
  },
  {
    id: '3',
    name: 'Dr. Carlos Rodríguez',
    specialty: 'Dermatología',
    medicalCenter: 'Centro Dermatológico Piel Sana',
    patients: 700,
    experience: '12 años',
    rating: 4.7,
    reviews: 280,
    aboutMe: 'Dermatólogo experto en enfermedades de la piel y procedimientos cosméticos.',
    workHours: 'Martes a Sábado: 10:00 AM - 4:00 PM',
    imageUrl: 'https://example.com/doctor3.jpg',
  },
  {
    id: '4',
    name: 'Dra. Mariana Gómez',
    specialty: 'Odontología',
    medicalCenter: 'Clínica Dental Sonrisa Radiante',
    patients: 1500,
    experience: '8 años',
    rating: 4.6,
    reviews: 200,
    aboutMe: 'Odontóloga enfocada en tratamientos de ortodoncia y estética dental.',
    workHours: 'Lunes a Viernes: 9:00 AM - 6:00 PM',
    imageUrl: 'https://example.com/doctor4.jpg',
  },
  {
    id: '5',
    name: 'Dr. José Torres',
    specialty: 'Neurología',
    medicalCenter: 'Hospital Cerebro Sano',
    patients: 1100,
    experience: '14 años',
    rating: 4.9,
    reviews: 350,
    aboutMe: 'Experto en el tratamiento de enfermedades neurológicas y trastornos cerebrales.',
    workHours: 'Lunes a Jueves: 10:00 AM - 4:00 PM',
    imageUrl: 'https://example.com/doctor5.jpg',
  },
  {
    id: '6',
    name: 'Dra. Patricia Silva',
    specialty: 'Ginecología',
    medicalCenter: 'Centro de Salud Femenina',
    patients: 950,
    experience: '9 años',
    rating: 4.8,
    reviews: 270,
    aboutMe: 'Especialista en salud femenina, con un enfoque en el bienestar reproductivo.',
    workHours: 'Lunes a Viernes: 8:30 AM - 4:30 PM',
    imageUrl: 'https://example.com/doctor6.jpg',
  },
  {
    id: '7',
    name: 'Dr. Ricardo Martínez',
    specialty: 'Oftalmología',
    medicalCenter: 'Clínica Visual Perfecta',
    patients: 1300,
    experience: '11 años',
    rating: 4.7,
    reviews: 290,
    aboutMe: 'Oftalmólogo especializado en el tratamiento de problemas visuales y cirugías láser.',
    workHours: 'Lunes a Sábado: 9:00 AM - 5:00 PM',
    imageUrl: 'https://example.com/doctor7.jpg',
  },
  {
    id: '8',
    name: 'Dra. Laura Herrera',
    specialty: 'Psiquiatría',
    medicalCenter: 'Hospital Mental Bienestar',
    patients: 600,
    experience: '7 años',
    rating: 4.9,
    reviews: 150,
    aboutMe: 'Psiquiatra con un enfoque integral en la salud mental y el bienestar emocional.',
    workHours: 'Martes a Viernes: 10:00 AM - 3:00 PM',
    imageUrl: 'https://example.com/doctor8.jpg',
  },
  {
    id: '9',
    name: 'Dr. Fernando Ruiz',
    specialty: 'General',
    medicalCenter: 'Clínica Hormonal Balance',
    patients: 500,
    experience: '6 años',
    rating: 4.6,
    reviews: 140,
    aboutMe: 'Endocrinólogo especializado en el tratamiento de trastornos hormonales y metabólicos.',
    workHours: 'Lunes a Jueves: 9:30 AM - 4:30 PM',
    imageUrl: 'https://example.com/doctor9.jpg',
  },
  {
    id: '10',
    name: 'Dra. Sofía Méndez',
    specialty: 'General',
    medicalCenter: 'Centro de Reumatología Avanzada',
    patients: 400,
    experience: '5 años',
    rating: 4.7,
    reviews: 120,
    aboutMe: 'Reumatóloga enfocada en el tratamiento de enfermedades autoinmunes y problemas articulares.',
    workHours: 'Lunes a Viernes: 10:00 AM - 5:00 PM',
    imageUrl: 'https://example.com/doctor10.jpg',
  },
];

export default doctorsData;
