const doctorsData = [
  {
    id: '1',
    name: 'Dr. John Smith',
    specialty: 'Cardiology',
    medicalCenter: 'Healthy Heart Clinic',
    patients: 1200,
    experience: '15 years',
    rating: 4.8,
    reviews: 320,
    aboutMe: 'Specialist in cardiology with over 15 years of experience helping patients with cardiovascular problems.',
    workHours: 'Monday to Friday: 9:00 AM - 5:00 PM',
    imageUrl: require('../../../assets/docNaranja.png'),
  },
  {
    id: '2',
    name: 'Dr. Ana Pérez',
    specialty: 'Pediatrics',
    medicalCenter: 'Joyful Child Hospital',
    patients: 900,
    experience: '10 years',
    rating: 4.9,
    reviews: 410,
    aboutMe: 'Passionate about child health, with a focus on development and well-being of children.',
    workHours: 'Monday to Friday: 8:00 AM - 3:00 PM',
    imageUrl: 'C:Sexto SemestreProgramacion movilTeleMedicinaproyecto_movil_frontassetsdocBlanco.png',
  },
  {
    id: '3',
    name: 'Dr. Carlos Rodríguez',
    specialty: 'Dermatology',
    medicalCenter: 'Healthy Skin Dermatology Center',
    patients: 700,
    experience: '12 years',
    rating: 4.7,
    reviews: 280,
    aboutMe: 'Expert dermatologist in skin diseases and cosmetic procedures.',
    workHours: 'Tuesday to Saturday: 10:00 AM - 4:00 PM',
    imageUrl: 'https://example.com/doctor3.jpg',
  },
  {
    id: '4',
    name: 'Dr. Mariana Gómez',
    specialty: 'Dentistry',
    medicalCenter: 'Radiant Smile Dental Clinic',
    patients: 1500,
    experience: '8 years',
    rating: 4.6,
    reviews: 200,
    aboutMe: 'Dentist focused on orthodontic and cosmetic treatments.',
    workHours: 'Monday to Friday: 9:00 AM - 6:00 PM',
    imageUrl:
      'C:Sexto SemestreProgramacion movilTeleMedicinaproyecto_movil_frontassetsdocRosa.pnghttps://example.com/doctor4.jpg',
  },
  {
    id: '5',
    name: 'Dr. José Torres',
    specialty: 'Neurology',
    medicalCenter: 'Healthy Brain Hospital',
    patients: 1100,
    experience: '14 years',
    rating: 4.9,
    reviews: 350,
    aboutMe: 'Expert in treating neurological diseases and brain disorders.',
    workHours: 'Monday to Thursday: 10:00 AM - 4:00 PM',
    imageUrl: 'https://example.com/doctor5.jpg',
  },
  {
    id: '6',
    name: 'Dr. Patricia Silva',
    specialty: 'Gynecology',
    medicalCenter: "Women's Health Center",
    patients: 950,
    experience: '9 years',
    rating: 4.8,
    reviews: 270,
    aboutMe: "Specialist in women's health, focusing on reproductive well-being.",
    workHours: 'Monday to Friday: 8:30 AM - 4:30 PM',
    imageUrl: 'C:Sexto SemestreProgramacion movilTeleMedicinaproyecto_movil_frontassetsdocVerde.png',
  },
  {
    id: '7',
    name: 'Dr. Ricardo Martínez',
    specialty: 'Ophthalmology',
    medicalCenter: 'Perfect Vision Clinic',
    patients: 1300,
    experience: '11 years',
    rating: 4.7,
    reviews: 290,
    aboutMe: 'Ophthalmologist specializing in visual problems and laser surgeries.',
    workHours: 'Monday to Saturday: 9:00 AM - 5:00 PM',
    imageUrl: 'https://example.com/doctor7.jpg',
  },
  {
    id: '8',
    name: 'Dr. Laura Herrera',
    specialty: 'Psychiatry',
    medicalCenter: 'Mental Well-being Hospital',
    patients: 600,
    experience: '7 years',
    rating: 4.9,
    reviews: 150,
    aboutMe: 'Psychiatrist with a holistic approach to mental health and emotional well-being.',
    workHours: 'Tuesday to Friday: 10:00 AM - 3:00 PM',
    imageUrl: 'https://example.com/doctor8.jpg',
  },
  {
    id: '9',
    name: 'Dr. Fernando Ruiz',
    specialty: 'General',
    medicalCenter: 'Hormonal Balance Clinic',
    patients: 500,
    experience: '6 years',
    rating: 4.6,
    reviews: 140,
    aboutMe: 'Endocrinologist specialized in treating hormonal and metabolic disorders.',
    workHours: 'Monday to Thursday: 9:30 AM - 4:30 PM',
    imageUrl: 'https://example.com/doctor9.jpg',
  },
  {
    id: '10',
    name: 'Dr. Sofía Méndez',
    specialty: 'General',
    medicalCenter: 'Healthy Heart Clinic',
    patients: 400,
    experience: '5 years',
    rating: 4.7,
    reviews: 120,
    aboutMe: 'Rheumatologist focused on autoimmune diseases and joint problems.',
    workHours: 'Monday to Friday: 10:00 AM - 5:00 PM',
    imageUrl: 'https://example.com/doctor10.jpg',
  },
];

export default doctorsData;
